language: generic
group: travis_latest
sudo: false

# whitelist
branches:
    only:
        - master
        - develop

env:
  global:
    - PYTHON_VERSION=2.7
    - CODECOV=true
    - PYTEST_FLAGS="-v --disable-pytest-warnings --durations=20 --low-performance --cov=gromacs"
    - PYTEST_LIST="gromacs/tests"
    - MAIN_CMD="pytest ${PYTEST_LIST}"
    - SETUP_CMD="${PYTEST_FLAGS}"
    - BUILD_CMD="pip install -v ."
    - CONDA_DEPENDENCIES="six scipy pandas gromacs"
    # Gromacs 2018 packages from bioconda require conda-forge for
    # dependency, see https://bioconda.github.io/#set-up-channels
    - CONDA_CHANNELS="defaults conda-forge bioconda"
    - CONDA_CHANNEL_PRIORITY=True
    - PIP_DEPENDENCIES="numkit codecov"
    - NUMPY_VERSION=stable

  matrix:
    # use ci-helper's PACKAGENAME_VERSION magic to pin the 'gromacs' package
    - GROMACS_VERSION=4.6.5   PYTHON_VERSION=2.7
    - GROMACS_VERSION=2018.2  PYTHON_VERSION=2.7 CODECOV=false
    - GROMACS_VERSION=4.6.5   PYTHON_VERSION=3.6
    - GROMACS_VERSION=2018.2  PYTHON_VERSION=3.6 CODECOV=false


matrix:
  fast_finish: true

  include:
    # note: no OSX Gromacs 2018 packages on bioconda https://anaconda.org/bioconda/gromacs/files
    - os: osx
      env: GROMACS_VERSION=4.6.5 PYTHON_VERSION=2.7
    - os: osx
      env: GROMACS_VERSION=4.6.5 PYTHON_VERSION=3.6
    
install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - eval $BUILD_CMD

script:
  - cd ${TRAVIS_BUILD_DIR}
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ulimit -S -n 2048; fi
  - echo $MAIN_CMD $SETUP_CMD
  - eval $MAIN_CMD $SETUP_CMD

after_success:
  - |
    if [[ $CODECOV == 'true' ]]; then \
      codecov; \
    fi
